package crossplane

import (
	"context"
	"fmt"
	"sort"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// XRDSchema is the API contract of one version of a platform API, extracted
// from the XRD that defines it.
//
// This is what somebody needs in order to write a valid composite resource or
// claim: the exact apiVersion and kind, and the shape of spec.
type XRDSchema struct {
	Name          string `json:"name"`
	Group         string `json:"group"`
	Version       string `json:"version"`
	CompositeKind string `json:"compositeKind"`
	ClaimKind     string `json:"claimKind,omitempty"`
	Scope         string `json:"scope,omitempty"`
	Served        bool   `json:"served"`
	Referenceable bool   `json:"referenceable"`

	// APIVersion is the value to put in a manifest, e.g. "example.org/v1".
	APIVersion string `json:"apiVersion"`
	// Spec is the OpenAPI schema of the spec field, which is the only part a
	// user writes. The rest of the schema is generated by Crossplane.
	Spec map[string]any `json:"spec,omitempty"`
	// Required lists the mandatory top level fields of spec.
	Required []string `json:"required,omitempty"`
	// Example is a minimal manifest that satisfies the required fields.
	Example string `json:"example,omitempty"`
}

// XRDSchemaFor returns the schema of one version of an XRD. An empty version
// selects the first served version, which is what a caller almost always
// wants.
func (c *Client) XRDSchemaFor(ctx context.Context, name, version string) (*XRDSchema, error) {
	resource, err := c.ResolveKind(ctx, "CompositeResourceDefinition", GroupAPIExtensions)
	if err != nil {
		return nil, err
	}
	obj, err := c.Get(ctx, resource, "", name)
	if err != nil {
		return nil, err
	}

	selected, err := selectVersion(obj, version)
	if err != nil {
		return nil, err
	}
	return xrdSchema(obj, selected), nil
}

// XRDSchemas returns every version declared by every XRD in the cluster.
//
// Unlike API discovery, this reads the XRD objects directly, so callers can
// reconcile a live catalog when definitions are installed or removed.
func (c *Client) XRDSchemas(ctx context.Context) ([]*XRDSchema, error) {
	resource, err := c.ResolveKind(ctx, "CompositeResourceDefinition", GroupAPIExtensions)
	if err != nil {
		return nil, err
	}
	objects, err := c.List(ctx, resource, ListOptions{})
	if err != nil {
		return nil, err
	}

	schemas := make([]*XRDSchema, 0, len(objects.Items))
	for i := range objects.Items {
		obj := &objects.Items[i]
		for _, item := range nestedSlice(obj, "spec", "versions") {
			version, ok := item.(map[string]any)
			if !ok || stringField(version, "name") == "" {
				continue
			}
			schemas = append(schemas, xrdSchema(obj, version))
		}
	}
	sort.Slice(schemas, func(i, j int) bool {
		if schemas[i].Group != schemas[j].Group {
			return schemas[i].Group < schemas[j].Group
		}
		if schemas[i].CompositeKind != schemas[j].CompositeKind {
			return schemas[i].CompositeKind < schemas[j].CompositeKind
		}
		return schemas[i].Version < schemas[j].Version
	})
	return schemas, nil
}

// XRDSchemaForType returns an XRD schema identified by its user-facing API
// group, composite kind and version.
func (c *Client) XRDSchemaForType(ctx context.Context, group, kind, version string) (*XRDSchema, error) {
	schemas, err := c.XRDSchemas(ctx)
	if err != nil {
		return nil, err
	}
	for _, schema := range schemas {
		if schema.Group == group && schema.CompositeKind == kind && schema.Version == version {
			return schema, nil
		}
	}
	return nil, &ErrNotFound{What: fmt.Sprintf("XRD schema %s/%s/%s", group, kind, version)}
}

func xrdSchema(obj *unstructured.Unstructured, selected map[string]any) *XRDSchema {
	schema := &XRDSchema{
		Name:          obj.GetName(),
		Group:         nestedString(obj, "spec", "group"),
		CompositeKind: nestedString(obj, "spec", "names", "kind"),
		ClaimKind:     nestedString(obj, "spec", "claimNames", "kind"),
		Scope:         nestedString(obj, "spec", "scope"),
	}

	schema.Version = stringField(selected, "name")
	schema.APIVersion = schema.Group + "/" + schema.Version
	schema.Served, _ = selected["served"].(bool)
	schema.Referenceable, _ = selected["referenceable"].(bool)

	// Crossplane nests the user facing contract under spec; everything above
	// it is boilerplate that Crossplane generates.
	if open, ok := selected["schema"].(map[string]any); ok {
		if v3, ok := open["openAPIV3Schema"].(map[string]any); ok {
			if properties, ok := v3["properties"].(map[string]any); ok {
				if spec, ok := properties["spec"].(map[string]any); ok {
					schema.Spec = spec
					schema.Required = stringSlice(spec["required"])
				}
			}
		}
	}
	schema.Example = exampleManifest(schema)
	return schema
}

// selectVersion picks the requested version, or the first served one.
func selectVersion(obj *unstructured.Unstructured, want string) (map[string]any, error) {
	versions := nestedSlice(obj, "spec", "versions")
	if len(versions) == 0 {
		return nil, fmt.Errorf("XRD %q declares no versions", obj.GetName())
	}

	available := make([]string, 0, len(versions))
	var firstServed map[string]any
	for _, item := range versions {
		entry, ok := item.(map[string]any)
		if !ok {
			continue
		}
		name := stringField(entry, "name")
		available = append(available, name)
		if want != "" && name == want {
			return entry, nil
		}
		if served, ok := entry["served"].(bool); ok && served && firstServed == nil {
			firstServed = entry
		}
	}

	if want != "" {
		sort.Strings(available)
		return nil, fmt.Errorf("XRD %q has no version %q, it has %v", obj.GetName(), want, available)
	}
	if firstServed == nil {
		return nil, fmt.Errorf("XRD %q serves no version", obj.GetName())
	}
	return firstServed, nil
}

// exampleManifest builds the smallest manifest that would pass validation, so
// that a caller has something to edit rather than something to invent.
func exampleManifest(schema *XRDSchema) string {
	if schema.APIVersion == "" || schema.CompositeKind == "" {
		return ""
	}

	manifest := fmt.Sprintf("apiVersion: %s\nkind: %s\nmetadata:\n  name: example\n",
		schema.APIVersion, schema.CompositeKind)
	if schema.Scope == "Namespaced" {
		manifest += "  namespace: default\n"
	}

	if len(schema.Required) == 0 {
		return manifest + "spec: {}\n"
	}

	properties, _ := schema.Spec["properties"].(map[string]any)
	manifest += "spec:\n"
	for _, field := range schema.Required {
		manifest += fmt.Sprintf("  %s: %s\n", field, placeholderFor(properties, field))
	}
	return manifest
}

// placeholderFor guesses a syntactically valid value for a required field.
func placeholderFor(properties map[string]any, field string) string {
	property, _ := properties[field].(map[string]any)
	switch stringField(property, "type") {
	case "integer", "number":
		return "0"
	case "boolean":
		return "false"
	case "array":
		return "[]"
	case "object":
		return "{}"
	default:
		return "\"\"  # TODO"
	}
}

func stringSlice(value any) []string {
	items, ok := value.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out
}
